seed: 2022
debug: false  # set debug=False for Full Training
first_batch: 54
all_batch: 80
srate: 250
windowLength: 14
windowStep: 4
trial_start: 240
trial_end: 241

trainer_name: CrossVal
model_name: MACTN
train_bs: 16
val_bs: 16
epochs: 100
lr: 0.001
l2norm: 0.0001
T_0: 10
min_lr: 1.0e-7

accum_iter: 2
verbose_step: 1
flood_b: 0.5

n_fold: 10
num_classes: 9
device: 0
ckpt_dir: './ckpt'
ckpt_name: 'Emotion'
patience: 10
earlystop_patience: 15
min_delta: 0

low_cut: 4
high_cut: 47
re_srate: 125
bp_low: 0.5
bp_high: 45
bs_low: 48
bs_high: 52
rerefence_type: 'bipolar_std'
channels: 30
use_de_feature: false
freq_bands: [[1, 3], [4, 7], [8, 13], [14, 30], [30, 45]]
is_save_model: true

input_shape: [30, 1750]